-- Better Auth core schema (Phase 9D-1B). Generated by `npx auth@latest
-- generate` from frontend/src/lib/auth/auth.ts (better-auth@1.7.5),
-- reviewed manually before integration, and applied through MedhOrbit's
-- own migration runner (scripts/migrate.mjs / npm run db:migrate) - not
-- Better Auth's own `migrate` command. Preserved exactly as generated;
-- no hand-authored changes.
--
-- No socialProviders are configured yet (Phase 9D-1B), and this migration
-- does not touch the worksheets table or add worksheets.owner_id - that
-- is Phase 9D-2.
--
-- Known upstream gap, reviewed and intentionally NOT worked around here:
-- the generated "account" table has no database-level
-- UNIQUE (providerId, accountId) constraint. This matches Better Auth's
-- own currently-shipped generated schema for 1.7.x (confirmed by
-- reproducing `generate` against this exact config) - Better Auth
-- enforces that identity pair at the application layer, not the
-- database layer. The project's own maintainers have an open,
-- unresolved discussion about restoring a DB-level constraint upstream
-- (better-auth/better-auth PR #11154, closed in favor of #11153, which
-- itself does not yet re-add the constraint). Preserving the
-- Better-Auth-generated schema as-is rather than diverging from it;
-- revisit if/when upstream ships a database-level constraint.

create table "user" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "session" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" uuid not null references "user" ("id") on delete cascade);

create table "account" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "accountId" text not null, "providerId" text not null, "userId" uuid not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");
