import { curriculum } from "./mock-data";
import { callClaudeAPI, ProviderError } from "./provider";
import { MAX_ANSWER_LENGTH, MAX_PROMPT_LENGTH, validateWorksheet } from "./validator";
import type {
  GenerateWorksheetRequest,
  GenerateWorksheetResponse,
  Question,
} from "./schema";

/** Class/subject pairs that may be generated by the AI provider. Extend to expand. */
const AI_SUPPORTED = [{ classId: "class-5", subjectId: "mathematics" }] as const;

const GENERIC_FAILURE = "We could not generate your worksheet. Please try again.";

/** Failure carrying an HTTP status and a message that is safe to show users. */
export class WorksheetGenerationError extends Error {
  constructor(
    message: string,
    readonly status: number,
  ) {
    super(message);
    this.name = "WorksheetGenerationError";
  }
}

/** Builds the generation prompt from catalog labels; no textbook content. */
function buildPrompt(
  request: GenerateWorksheetRequest,
  labels: { classLabel: string; subjectLabel: string; topicLabel: string },
): string {
  return [
    "You write practice worksheets for Indian CBSE school students.",
    `Class: ${labels.classLabel} (CBSE)`,
    `Subject: ${labels.subjectLabel}`,
    "Textbook context: Math Mela (a curriculum reference only; do not reproduce textbook text).",
    `Topic: ${labels.topicLabel}`,
    `Difficulty: ${request.difficulty}`,
    `Number of questions: ${request.questionCount}`,
    "",
    `Write exactly ${request.questionCount} original questions on this topic, suitable for the class and difficulty above.`,
    "Each question must be self-contained, use plain text only, and have a short correct answer.",
    'Respond with JSON only, in the form {"questions":[{"prompt":"...","answer":"..."}]}.',
  ].join("\n");
}

/** Parses and validates the model reply; throws if anything is off. */
function parseQuestions(
  text: string,
  expectedCount: number,
): { prompt: string; answer: string }[] {
  const json = text.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");

  let data: unknown;
  try {
    data = JSON.parse(json);
  } catch {
    throw new Error("Response was not valid JSON.");
  }

  if (typeof data !== "object" || data === null || Array.isArray(data)) {
    throw new Error("Response was not a JSON object.");
  }
  const questions = (data as Record<string, unknown>).questions;
  if (!Array.isArray(questions)) {
    throw new Error("Response 'questions' was not an array.");
  }
  if (questions.length !== expectedCount) {
    throw new Error(`Expected ${expectedCount} questions, received ${questions.length}.`);
  }

  return questions.map((item, index) => {
    if (typeof item !== "object" || item === null) {
      throw new Error(`Question ${index + 1} was not an object.`);
    }
    const { prompt, answer } = item as Record<string, unknown>;
    if (typeof prompt !== "string" || prompt.trim() === "" || prompt.length > MAX_PROMPT_LENGTH) {
      throw new Error(`Question ${index + 1} has an invalid prompt.`);
    }
    if (typeof answer !== "string" || answer.trim() === "" || answer.length > MAX_ANSWER_LENGTH) {
      throw new Error(`Question ${index + 1} has an invalid answer.`);
    }
    return { prompt: prompt.trim(), answer: answer.trim() };
  });
}

// Phase 7A issue codes that mean the *validation system* itself failed
// (bad/missing evaluator reply), as opposed to a worksheet quality problem.
// These are never retried - retrying a broken check wastes a call for
// nothing, per Phase 7B's "system failure vs quality failure" distinction.
const SYSTEM_FAILURE_CODES = new Set(["evaluator_malformed", "evaluator_count_mismatch"]);

function isSystemFailure(validation: Awaited<ReturnType<typeof validateWorksheet>>): boolean {
  return validation.issues.some((issue) => issue.severity === "error" && SYSTEM_FAILURE_CODES.has(issue.code));
}

const MAX_GENERATION_ATTEMPTS = 2;
const RETRY_HINT = "\n\nThis is a retry attempt. Generate a different set of questions.";

/**
 * Generates a worksheet with Claude. The catalog lookup, question ids and all
 * metadata are server-owned; the model supplies only prompt and answer text.
 * Throws WorksheetGenerationError; never returns a partial worksheet.
 *
 * Retries generation once (max 2 attempts total) if Phase 7A validation
 * finds a critical worksheet-quality failure (e.g. duplicates, an incorrect
 * answer, an off-topic question). Non-quality failures - missing config,
 * invalid requests, provider/network errors, malformed model or evaluator
 * output - fail immediately and are never retried.
 */
export async function generateWorksheet(
  request: GenerateWorksheetRequest,
): Promise<GenerateWorksheetResponse> {
  const selectedClass = curriculum.find((item) => item.id === request.classId);
  const subject = selectedClass?.subjects.find((item) => item.id === request.subjectId);
  const topic = subject?.topics.find((item) => item.id === request.topicId);
  if (!selectedClass || !subject || !topic) {
    throw new WorksheetGenerationError(
      "The selected class, subject, or topic is not supported.",
      400,
    );
  }

  if (!AI_SUPPORTED.some((item) => item.classId === request.classId && item.subjectId === request.subjectId)) {
    throw new WorksheetGenerationError(
      "AI generation is not available for the selected class and subject.",
      400,
    );
  }

  const basePrompt = buildPrompt(request, {
    classLabel: selectedClass.label,
    subjectLabel: subject.label,
    topicLabel: topic.label,
  });

  for (let attempt = 1; attempt <= MAX_GENERATION_ATTEMPTS; attempt++) {
    const prompt = attempt === 1 ? basePrompt : `${basePrompt}${RETRY_HINT}`;

    let text: string;
    try {
      text = await callClaudeAPI(prompt);
    } catch (error) {
      if (error instanceof ProviderError) {
        console.error("[worksheets/service] provider failure:", error.kind, error.status ?? "");
        if (error.kind === "missing_key") {
          throw new WorksheetGenerationError(
            "Worksheet generation is not configured on the server.",
            500,
          );
        }
        throw new WorksheetGenerationError(GENERIC_FAILURE, 502);
      }
      console.error("[worksheets/service] unexpected provider error:", error instanceof Error ? error.name : "unknown");
      throw new WorksheetGenerationError(GENERIC_FAILURE, 500);
    }

    let generated: { prompt: string; answer: string }[];
    try {
      generated = parseQuestions(text, request.questionCount);
    } catch (error) {
      console.error("[worksheets/service] invalid model output:", error instanceof Error ? error.message : "unknown");
      throw new WorksheetGenerationError(GENERIC_FAILURE, 502);
    }

    let validation: Awaited<ReturnType<typeof validateWorksheet>>;
    try {
      validation = await validateWorksheet({
        classLabel: selectedClass.label,
        subjectLabel: subject.label,
        topicLabel: topic.label,
        difficulty: request.difficulty,
        questions: generated,
      });
    } catch (error) {
      console.error(
        "[worksheets/service] validation run threw unexpectedly:",
        error instanceof Error ? error.message : "unknown",
      );
      throw new WorksheetGenerationError(GENERIC_FAILURE, 502);
    }

    if (validation.isValid) {
      const warningCodes = validation.issues.map((issue) => issue.code);
      if (warningCodes.length > 0) {
        console.log("[worksheets/service] worksheet passed validation with warnings:", warningCodes.join(", "));
      } else {
        console.log("[worksheets/service] worksheet passed validation.");
      }

      const questions: Question[] = generated.map((item, index) => ({
        id: `${request.topicId}-${request.difficulty}-${index + 1}`,
        prompt: item.prompt,
        type: "short-answer",
        answer: item.answer,
      }));

      return {
        questions,
        metadata: {
          classId: request.classId,
          subjectId: request.subjectId,
          topicId: request.topicId,
          difficulty: request.difficulty,
          questionCount: request.questionCount,
          generated: new Date().toISOString(),
        },
      };
    }

    const codes = validation.issues.map((issue) => issue.code).join(", ");
    const indices = validation.issues
      .map((issue) => issue.questionIndex)
      .filter((index): index is number => typeof index === "number");

    if (isSystemFailure(validation) || attempt === MAX_GENERATION_ATTEMPTS) {
      console.error(
        `[worksheets/service] worksheet failed validation (attempt ${attempt}/${MAX_GENERATION_ATTEMPTS}, no retry):`,
        `codes=[${codes}]`,
        `questionIndices=[${indices.join(",")}]`,
      );
      throw new WorksheetGenerationError(GENERIC_FAILURE, 502);
    }

    console.warn(
      `[worksheets/service] worksheet failed validation (attempt ${attempt}/${MAX_GENERATION_ATTEMPTS}), retrying:`,
      `codes=[${codes}]`,
      `questionIndices=[${indices.join(",")}]`,
    );
  }

  // Unreachable: the loop above always returns or throws before exhausting
  // MAX_GENERATION_ATTEMPTS.
  throw new WorksheetGenerationError(GENERIC_FAILURE, 502);
}
